version: "3.8"
services:
  anime-db:
    image: postgres:13
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: animeadmin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    networks:
      - ani-me
networks:
  ani-me: